export const revData = [
  {name: "Medical Center", color: "#F0BF00", "info": "A large, not-for-profit regional medical center, including multiple hospitals, labs and clinics. Income comes from patients, medical insurance companies, and government programs like medicare.", value: 45},
  {name: "Student Fees", color: "#5F63EC", info: "Fees are dedicated to specific services, such as athletic facilities, bus service (UNITRANS), student organizations, the CoHo and Student Community Center, etc.", value: 4},
  {name: "State of California", color: "#F6E50E", info: "General funds given by the taxpayers of California, appropriated annualy by the state legislature. General funds are not dedicated to specific services. ", value: 8},
  {name: "Tuition", color: "#FFF688", info: "Students pay tuition to attend the University. Non-California residents pay about twice as much as residents.  Tuition is also general funds.", value: 11},
  {name: "Research Grants and Contracts", color: "#71A8FF", info: "Government and industry funds given to faculty and graduate students to perform research projects. These include up to 50% overhead in addition to the cost of the research.", value: 13},
  {name: "Pell Grants", color: "#D4E4FF", info: "Federal grants for tuition and living expenses for low-income students. Percentage of students with Pell grants is a good way to measure who a University serves; at UCD, it's 34%; at Cal Tech it's 14%; at Sac State it's 71%.", value: 1},
  {name: "Non-educationsal Services", color: "lightblue", info: "Services other than education that people pay for, like dorms, dining, parking, etc.  At UC Davis, this also includes almost $500M of revenue generated by medical school faculty, or 8%, making this category look really big.", value: 11},
  {name: "Gifts, Endowments, Interest, etc", color: "#0F7AB4", info: "Endowments are past gifts that were invested to provide income; interest is earned on other savings. The Museum is the direct result of a $10M gift from Jan Shrem and Maria Manetti Shrem.", value: 7}];

export const expData = [
  {name: "Medical Center", color: "#F0BF00", info: "The cost of providing care at the Medical Center is roughly what we get paid to provide it.", value: 43},
  {name: "Teaching and Teaching Support", color: "#F6E50E", info: "Professors, advisors, deans, the library, the computer labs, etc, including Medical School faculty salaries.", value: 23},
  {name: "Research", color: "#FFF688", info: "The costs of doing the research, mostly researcher salaries. ", value: 11},
  {name: "Student Services and Financial Aid", color: "#5F63EC", info: "Student Health, things covered by fees, Admissions, and also financial aid from the general funds, which is about $100M or 1.5%.", value: 8},
  {name: "Operation and Maintenance", color: "#58C9FB", info: "Upkeep of the grounds and building, and utilities, which are less than 1%.", value: 2},
  {name: "Administration", color: "#D4E4FF", info: "Provost and Chancellor's offices, raising money, accounting, personnel, legal, making budgets. ", value: 3},
  {name: "Services", color: "#0F7AB4", info:"The costs of providing dorms, dining, parking, etc.", value: 2},
  {name: "Public Service", color:"white", info:"Mostly the cooperative extension, which provides agricultural services to farmers, ranchers, winemakers, etc.  Part of our mission as a land grant university. ", value: 2},
  {name: "Depreciation, Interest, etc.", color: "#71A8FF", info: "Depreciation is the loss of value of buildings and equipment as they wear out. Mostly unavoidable financial losses. ", value: 6}];